---
#-- Ansible playbook to install Docker and expose docker API to Jenkins ----#

- hosts: all
  become: yes

  roles:
     - geerlingguy.docker
  tasks:
     - name: Expose TCP for docker API
       lineinfile:
         path: /usr/lib/systemd/system/docker.service
         state: present
         regexp: '^ExecStart'
         line: "ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"

     - name: Restart docker
       service: name=docker state=restarted
